version: "3"

services:
  #ssd 
  sshd:
    image: rome314/openssh:latest
    ports:
      - "23:22" #docker sshd will listen port 23
    volumes:
      - ./sshd-configuration/authorized_keys:/root/.ssh/authorized_keys #file with authorized keys mounting
      - ./sshd-configuration/sshd_config:/etc/ssh/sshd_config #config file mountin
    networks:
      - internal_nw #network to communicate with other containers
      - external_nw #network with internet access

  # Application
  db:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - internal_nw #acceptable only from internal network
    restart: always

  hackmd:
    image: hackmdio/hackmd:1.3.1-alpine
    environment:
      - HMD_DB_URL=postgres://hackmd:hackmdpass@db:5432/hackmd
    ports:
      - "3000"
    networks:
      - internal_nw  #acceptable only from internal network
    restart: always
    depends_on:
      - db

networks:
  internal_nw:
    internal: true
    driver: bridge
  external_nw:

volumes:
  database:

